POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "admin",
    "firstName": "Test",
    "lastName": "Admin",
    "email": "admin@example.com",
    "password": "testpassword",
    "role": "admin"
}